// Sample data for Hamilton, Ontario, Canada
export const sampleData = {
  safeZones: [
    {
      id: 'sz1',
      name: 'Hamilton Emergency Shelter',
      type: 'Shelter',
      address: '155 James St N, Hamilton, ON L8R 2K9',
      lat: 43.2567,
      lng: -79.8694,
      capacity: 200,
      occupancy: 145,
      supplies: {
        food: 75,
        water: 80,
        medical: 60,
        blankets: 90
      }
    },
    {
      id: 'sz2',
      name: 'McMaster University Medical Centre',
      type: 'Hospital',
      address: '1200 Main St W, Hamilton, ON L8N 3Z5',
      lat: 43.2609,
      lng: -79.9192,
      capacity: 500,
      occupancy: 320,
      supplies: {
        food: 50,
        water: 70,
        medical: 95,
        blankets: 40
      }
    },
    {
      id: 'sz3',
      name: 'FirstOntario Centre',
      type: 'Aid Station',
      address: '101 York Blvd, Hamilton, ON L8R 3L4',
      lat: 43.2581,
      lng: -79.8778,
      capacity: 1000,
      occupancy: 650,
      supplies: {
        food: 45,
        water: 55,
        medical: 70,
        blankets: 80
      }
    },
    {
      id: 'sz4',
      name: 'Hamilton General Hospital',
      type: 'Hospital',
      address: '237 Barton St E, Hamilton, ON L8L 2X2',
      lat: 43.2536,
      lng: -79.8503,
      capacity: 400,
      occupancy: 280,
      supplies: {
        food: 60,
        water: 65,
        medical: 90,
        blankets: 50
      }
    },
    {
      id: 'sz5',
      name: 'Westdale Community Centre',
      type: 'Shelter',
      address: '955 King St W, Hamilton, ON L8S 1K8',
      lat: 43.2644,
      lng: -79.9067,
      capacity: 150,
      occupancy: 95,
      supplies: {
        food: 70,
        water: 75,
        medical: 50,
        blankets: 85
      }
    },
    {
      id: 'sz6',
      name: 'St. Joseph\'s Healthcare Hamilton',
      type: 'Hospital',
      address: '50 Charlton Ave E, Hamilton, ON L8N 4A6',
      lat: 43.2431,
      lng: -79.8722,
      capacity: 350,
      occupancy: 210,
      supplies: {
        food: 55,
        water: 60,
        medical: 85,
        blankets: 45
      }
    },
    {
      id: 'sz7',
      name: 'Mohawk Sports Park',
      type: 'Aid Station',
      address: '385 Mohawk Rd W, Hamilton, ON L9C 1W1',
      lat: 43.2306,
      lng: -79.8889,
      capacity: 300,
      occupancy: 180,
      supplies: {
        food: 65,
        water: 70,
        medical: 55,
        blankets: 75
      }
    },
    {
      id: 'sz8',
      name: 'Dundas Community Centre',
      type: 'Shelter',
      address: '10 Market St S, Dundas, ON L9H 1A1',
      lat: 43.2658,
      lng: -79.9556,
      capacity: 120,
      occupancy: 75,
      supplies: {
        food: 80,
        water: 85,
        medical: 40,
        blankets: 90
      }
    }
  ],
  requests: [
    {
      id: 'req1',
      survivorId: 'surv1',
      survivorName: 'Sarah Johnson',
      survivorPhone: '905-555-0101',
      type: 'Medical',
      urgency: 'High',
      peopleCount: 2,
      lat: 43.2550,
      lng: -79.8700,
      description: 'Elderly person needs medical attention, difficulty breathing',
      status: 'Pending',
      createdAt: new Date(Date.now() - 15 * 60000).toISOString()
    },
    {
      id: 'req2',
      survivorId: 'surv2',
      survivorName: 'Michael Chen',
      survivorPhone: '905-555-0102',
      type: 'Food/Water',
      urgency: 'High',
      peopleCount: 4,
      lat: 43.2600,
      lng: -79.8750,
      description: 'Family of 4, no food or water for 12 hours',
      status: 'Pending',
      createdAt: new Date(Date.now() - 30 * 60000).toISOString()
    },
    {
      id: 'req3',
      survivorId: 'surv3',
      survivorName: 'Emma Williams',
      survivorPhone: '905-555-0103',
      type: 'Evacuation',
      urgency: 'Urgent',
      peopleCount: 1,
      lat: 43.2500,
      lng: -79.8600,
      description: 'Trapped in building, need immediate evacuation',
      status: 'Assigned',
      assignedVolunteerId: 'vol1',
      assignedVolunteerName: 'John Smith',
      createdAt: new Date(Date.now() - 45 * 60000).toISOString()
    },
    {
      id: 'req4',
      survivorId: 'surv4',
      survivorName: 'David Brown',
      survivorPhone: '905-555-0104',
      type: 'Shelter',
      urgency: 'Medium',
      peopleCount: 3,
      lat: 43.2650,
      lng: -79.8800,
      description: 'Home damaged, need temporary shelter',
      status: 'Pending',
      createdAt: new Date(Date.now() - 60 * 60000).toISOString()
    },
    {
      id: 'req5',
      survivorId: 'surv5',
      survivorName: 'Lisa Anderson',
      survivorPhone: '905-555-0105',
      type: 'Medical',
      urgency: 'High',
      peopleCount: 1,
      lat: 43.2450,
      lng: -79.8650,
      description: 'Child injured, needs medical supplies',
      status: 'Pending',
      createdAt: new Date(Date.now() - 20 * 60000).toISOString()
    },
    {
      id: 'req6',
      survivorId: 'surv6',
      survivorName: 'Robert Taylor',
      survivorPhone: '905-555-0106',
      type: 'Food/Water',
      urgency: 'Medium',
      peopleCount: 2,
      lat: 43.2700,
      lng: -79.8900,
      description: 'Running low on supplies',
      status: 'Pending',
      createdAt: new Date(Date.now() - 90 * 60000).toISOString()
    },
    {
      id: 'req7',
      survivorId: 'surv7',
      survivorName: 'Jennifer Martinez',
      survivorPhone: '905-555-0107',
      type: 'Other',
      urgency: 'Low',
      peopleCount: 1,
      lat: 43.2400,
      lng: -79.8550,
      description: 'Need help with communication, phone battery dead',
      status: 'Pending',
      createdAt: new Date(Date.now() - 120 * 60000).toISOString()
    },
    {
      id: 'req8',
      survivorId: 'surv8',
      survivorName: 'James Wilson',
      survivorPhone: '905-555-0108',
      type: 'Evacuation',
      urgency: 'Urgent',
      peopleCount: 5,
      lat: 43.2750,
      lng: -79.9000,
      description: 'Large family needs evacuation assistance',
      status: 'Assigned',
      assignedVolunteerId: 'vol2',
      assignedVolunteerName: 'Maria Garcia',
      createdAt: new Date(Date.now() - 10 * 60000).toISOString()
    },
    {
      id: 'req9',
      survivorId: 'surv9',
      survivorName: 'Patricia Moore',
      survivorPhone: '905-555-0109',
      type: 'Shelter',
      urgency: 'High',
      peopleCount: 2,
      lat: 43.2350,
      lng: -79.8500,
      description: 'Elderly couple, home unsafe',
      status: 'Pending',
      createdAt: new Date(Date.now() - 75 * 60000).toISOString()
    },
    {
      id: 'req10',
      survivorId: 'surv10',
      survivorName: 'Christopher Lee',
      survivorPhone: '905-555-0110',
      type: 'Food/Water',
      urgency: 'Medium',
      peopleCount: 3,
      lat: 43.2800,
      lng: -79.9100,
      description: 'Family needs food and water supplies',
      status: 'Fulfilled',
      createdAt: new Date(Date.now() - 180 * 60000).toISOString(),
      completedAt: new Date(Date.now() - 60 * 60000).toISOString()
    },
    {
      id: 'req11',
      survivorId: 'surv11',
      survivorName: 'Amanda White',
      survivorPhone: '905-555-0111',
      type: 'Medical',
      urgency: 'High',
      peopleCount: 1,
      lat: 43.2300,
      lng: -79.8450,
      description: 'Need prescription medication',
      status: 'Pending',
      createdAt: new Date(Date.now() - 25 * 60000).toISOString()
    },
    {
      id: 'req12',
      survivorId: 'surv12',
      survivorName: 'Daniel Harris',
      survivorPhone: '905-555-0112',
      type: 'Evacuation',
      urgency: 'Medium',
      peopleCount: 2,
      lat: 43.2850,
      lng: -79.9150,
      description: 'Need transportation to safe zone',
      status: 'Pending',
      createdAt: new Date(Date.now() - 100 * 60000).toISOString()
    },
    {
      id: 'req13',
      survivorId: 'surv13',
      survivorName: 'Michelle Clark',
      survivorPhone: '905-555-0113',
      type: 'Food/Water',
      urgency: 'Urgent',
      peopleCount: 6,
      lat: 43.2250,
      lng: -79.8400,
      description: 'Large family, urgent need for food and water',
      status: 'Pending',
      createdAt: new Date(Date.now() - 5 * 60000).toISOString()
    },
    {
      id: 'req14',
      survivorId: 'surv14',
      survivorName: 'Kevin Lewis',
      survivorPhone: '905-555-0114',
      type: 'Shelter',
      urgency: 'High',
      peopleCount: 1,
      lat: 43.2900,
      lng: -79.9200,
      description: 'Homeless, need shelter immediately',
      status: 'Pending',
      createdAt: new Date(Date.now() - 40 * 60000).toISOString()
    },
    {
      id: 'req15',
      survivorId: 'surv15',
      survivorName: 'Nicole Walker',
      survivorPhone: '905-555-0115',
      type: 'Medical',
      urgency: 'Medium',
      peopleCount: 2,
      lat: 43.2200,
      lng: -79.8350,
      description: 'Need first aid supplies',
      status: 'Fulfilled',
      createdAt: new Date(Date.now() - 200 * 60000).toISOString(),
      completedAt: new Date(Date.now() - 80 * 60000).toISOString()
    },
    {
      id: 'req16',
      survivorId: 'surv16',
      survivorName: 'Brian Young',
      survivorPhone: '905-555-0116',
      type: 'Other',
      urgency: 'Low',
      peopleCount: 1,
      lat: 43.2950,
      lng: -79.9250,
      description: 'Need help moving belongings',
      status: 'Pending',
      createdAt: new Date(Date.now() - 110 * 60000).toISOString()
    },
    {
      id: 'req17',
      survivorId: 'surv17',
      survivorName: 'Stephanie King',
      survivorPhone: '905-555-0117',
      type: 'Evacuation',
      urgency: 'High',
      peopleCount: 3,
      lat: 43.2150,
      lng: -79.8300,
      description: 'Family with children needs evacuation',
      status: 'Pending',
      createdAt: new Date(Date.now() - 50 * 60000).toISOString()
    },
    {
      id: 'req18',
      survivorId: 'surv18',
      survivorName: 'Ryan Wright',
      survivorPhone: '905-555-0118',
      type: 'Food/Water',
      urgency: 'Medium',
      peopleCount: 2,
      lat: 43.3000,
      lng: -79.9300,
      description: 'Running low on supplies',
      status: 'Fulfilled',
      createdAt: new Date(Date.now() - 220 * 60000).toISOString(),
      completedAt: new Date(Date.now() - 100 * 60000).toISOString()
    },
    {
      id: 'req19',
      survivorId: 'surv19',
      survivorName: 'Lauren Lopez',
      survivorPhone: '905-555-0119',
      type: 'Medical',
      urgency: 'Urgent',
      peopleCount: 1,
      lat: 43.2100,
      lng: -79.8250,
      description: 'Severe injury, need immediate medical help',
      status: 'Assigned',
      assignedVolunteerId: 'vol3',
      assignedVolunteerName: 'Robert Johnson',
      createdAt: new Date(Date.now() - 8 * 60000).toISOString()
    },
    {
      id: 'req20',
      survivorId: 'surv20',
      survivorName: 'Tyler Hill',
      survivorPhone: '905-555-0120',
      type: 'Shelter',
      urgency: 'Medium',
      peopleCount: 4,
      lat: 43.3050,
      lng: -79.9350,
      description: 'Family needs temporary housing',
      status: 'Pending',
      createdAt: new Date(Date.now() - 130 * 60000).toISOString()
    }
  ],
  volunteers: []
};

